name: Issues Management with Releases

on:
  release:
    types: [published]

env:
  PROJECT_ID: 4

jobs:
  issue_management_with_release:
    if: ${{ !github.event.release.draft }}
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      id: setup
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      run: |
        gh api graphql -f query='
          query($user: String!) {
            user(login: $user) {
              projectV2(number: ${{ env.PROJECT_ID }}) {
                items(first: 100) {
                  nodes {
                    ... on ProjectV2Item {
                      id
                      fieldValues(first: 10, orderBy: { direction: DESC, field: POSITION}) {
                        nodes {
                          ... on ProjectV2ItemFieldValue {
                            ... on ProjectV2ItemFieldSingleSelectValue {
                              field {
                                ... on ProjectV2SingleSelectField {
                                  name
                                }
                              }
                              name
                            }
                            ... on ProjectV2ItemFieldTextValue {
                              field {
                                ... on ProjectV2Field {
                                  name
                                }
                              }
                              text
                            }
                          }
                        }
                      }
                    }
                  }
                }
                id
                fields(first: 20) {
                  nodes {
                    ... on ProjectV2SingleSelectField {
                      id
                      name
                      options {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }
          }
        ' -f user="${{ github.repository_owner }}" > card_data.json

        echo 'project_id'=$(jq '.data.user.projectV2.id' card_data.json) >> $GITHUB_OUTPUT
        echo 'status_field_id'=$(jq '.data.user.projectV2.fields.nodes[] | select(.name== "Status") | .id' card_data.json) >> $GITHUB_OUTPUT
        echo 'pending_release_value_id'=$(jq '.data.user.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name== "Pending Release") | .id' card_data.json) >> $GITHUB_OUTPUT
        echo 'released_value_id'=$(jq '.data.user.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name== "Released") | .id' card_data.json) >> $GITHUB_OUTPUT

    - name: Clone Repo
      id: clone_repo
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      run: |
        git clone --filter=blob:none --bare https://github.com/${{ github.repository }}.git repo

    - name: Process Issues
      id: process_issues
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      run: |
        cd repo

        add_comment='
          mutation(
            $issue: ID!
            $body: String!
          ) {
            addComment(input: {
              subjectId: $issue
              body: $body
            })
          }
        '

        close_issue='
          mutation(
            $issue: ID!
          ) {
            closeIssue(input: {
              issueId: $issue
            })
          }
        '

        move_item='
          mutation(
            $project: ID!
            $item: ID!
            $status_field: ID!
            $status_value: String!
          ) {
            updateProjectV2ItemFieldValue(input: {
                projectId: $project
                itemId: $item
                fieldId: $status_field
                value: { 
                  singleSelectOptionId: $status_value
                }
              }
            )
          }
        '

        is_id=true

        jq -c '.data.user.projectV2.items.nodes[] | .id as $node_id | .fieldValues.nodes | 
        reduce .[] as $fields ({}; 
        if $fields.field.name == "Status" then 
          .["Status"] = $fields.name 
        elif $fields.field.name == "Fixed Commit" then 
          .["Fixed Commit"] = $fields.text
        else
          .
        end) | select(.["Status"] == "Pending Release" and .["Fixed Commit"] != null) | $node_id, .["Fixed Commit"]' ../card_data.json | while read i; do
          echo $i
          if $is_id; then
            card_id=$i
            is_id=false
            continue
          else
            sha=$(echo $i | tr -d '"')
            is_id=true
          fi
          git branch --contains $sha | grep -E '(^|\s)master($|\s)' || continue
          echo $i is in master
          gh api graphql -f query="$move_item" -f project=${{ steps.setup.outputs.project_id }} -f item=$card_id -f status_field=${{ steps.setup.outputs.status_field_id }} -f status_value=${{ steps.setup.outputs.released_value_id }}
        done

        ${{ github.event.release.tag_name }}